### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Adarsh-Liju** [acmpesuecc/ProjectTurtle#1]
# Update README.md
The documentation of this project is not complete, yet! , well you have a chance by suggesting edits to documentation or changing some error in documentation

## Blocking Time

Max Blocking time for this issue is **30 min**

## Brownie Points

Brownie Points for fixing : **2-7points** [Depends on contribution]

> May the FOSS be with you

**Comment by AtharvaAnilChanda** [comment]
hey adarsh , i'd like to work on the documentation

**Comment by Adarsh-Liju** [comment]
Done @AtharvaAnilChanda

**Comment by Sushh-24** [comment]
@Adarsh-Liju can you assign this to me PES2UG21CS560?

**Comment by Adarsh-Liju** [comment]
Yes please do

**Comment by Adarsh-Liju** [comment]
The block period is over @Sushh-24 I have to remove you from this issue
