### ISSUE TITLE
Running Shell Commands for Go and Julia

### ISSUE THREAD

**Issue by NandanHemanth** [acmpesuecc/ProjectTurtle#12]
The Addition of new languages like "go" and "Julia" sounds exciting right? Why not implement this into this repo?
ISSUE : Need to append more frequently used, harder-to-install shell scripting commands(Apache-big data(extremely hard to install)) to this Repo

**Comment by Adarsh-Liju** [comment]
@NandanHemanth you can add `go` and `julia` , you can try apache

**Comment by Adarsh-Liju** [comment]
The blocking time is *4 hours* and bounty points is *40 points*
