### ISSUE TITLE
Add Docker installation

### ISSUE THREAD

**Issue by Adarsh-Liju** [acmpesuecc/ProjectTurtle#2]
# Docker installation
`docker` is very important for many developers worldwide, its installation can also be added to this shell script.Find a way to add it and give proper documentation in the form of comments 

## Blocking Time

Max Blocking time for this issue is **2 hours**

## Bounty Points

Bounty Points for fixing : **30 points**

> May the FOSS be with you

**Comment by NandanHemanth** [comment]
Working on this
PLease Lock this for me after OPEN ACCESS ends!

**Comment by Adarsh-Liju** [comment]
Done @NandanHemanth

**Comment by Adarsh-Liju** [comment]
@BhaviniMadhuranath has fixed the issue
