### ISSUE TITLE
Verfication Script

### ISSUE THREAD

**Issue by Adarsh-Liju** [acmpesuecc/ProjectTurtle#3]
# Verfication Script
After installation via the shell script , there is no script for verifying whether the particular tool , program,etc. is installed.

A shell script can be made to check whether  all programs are properly installed

Please use proper comments and coding style for the verification script 

## Blocking Time

Max Blocking time for this issue is **1.5 hour**
[You have to update progress every 1.5 hrs]

## Bounty Points

Bounty Points for fixing : **30 points**
 
> May the FOSS be with you

**Comment by BhaviniMadhuranath** [comment]
can i work on this?

**Comment by Adarsh-Liju** [comment]
Done @BhaviniMadhuranath

**Comment by Adarsh-Liju** [comment]
Try fixing this issue if you can
