### ISSUE TITLE
Testing Environment Setup

### ISSUE THREAD

**Issue by Adarsh-Liju** [acmpesuecc/ProjectTurtle#4]
# Testing Environment Setup

For testing the bash script , we require a `docker` container (ubuntu) 

## Pre-requisites 

The contributor should have really good knowledge of  `docker` and `bash`

## What it should do

It should execute the `menu.sh` script and check if its working properly.

## Block Time

Max Block Time is : **7 hours**
## Bounty Points

Bounty Points for this issue is : **60 points**

**Comment by NandanHemanth** [comment]
Lock this to me I will work on it

**Comment by Adarsh-Liju** [comment]
@NandanHemanth done boss

**Comment by Adarsh-Liju** [comment]
This issue is still open @NandanHemanth

**Comment by Adarsh-Liju** [comment]
You have to make a Dockerfile
