### ISSUE TITLE
Adding requirements.txt

### ISSUE THREAD

**Issue by Adarsh-Liju** [acmpesuecc/ProjectTurtle#5]
# Adding requirements.txt to the code

There are two text files `gui_requirements.txt` and `ml_requirements.txt`  , create a function that can install all modules using the format :-

```
pip3 install -r requirements 
```
## Coding Style

Please follow the function style used in this code, and call the function properly.
## Blocking Time

Maximum Blocking time for this issue is : **3 hours**

## Bounty points 

Bounty Points for this issue is : **40 points**

> May the FOSS be with you

**Comment by BhaviniMadhuranath** [comment]
can i work on this?

**Comment by Adarsh-Liju** [comment]
@NandanHemanth is working on this , I am seeing his PR

**Comment by NandanHemanth** [comment]
> can i work on this?

nah nah I'm already done working on it

**Comment by Adarsh-Liju** [comment]
He has solved the issue 
Thank you @NandanHemanth

**Comment by Adarsh-Liju** [comment]
!bounty 35
